### ISSUE TITLE
TypeError: 'dict_values' object does not support indexing

### ISSUE THREAD

**Issue by franz101** [chirjeev94/altcoin-trading-stratgey-catalyst#1]
my_altcoin_trading_strategy.ipynb

gives the following error:
TypeError: 'dict_values' object does not support indexing

I'm running it on docker.
---- FIXED IT:----
It's basically the difference of python 3 and python 2...
simply add a list in fron of your unpacked dict list(example_dict.values())

**Comment by chirjeev94** [comment]
Should work fine in Python 2.

**Comment by chirjeev94** [comment]
@franz101 Thank you for pointing it out :) I'll make the corresponding compatibility changes.
